name: provisioning an EC2 instance in AWS using terraform

on:
  push:
    branches: [main]          # 'branches' (plural), not 'branch'

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}         # use 'secrets' context, not 'vars'
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}        # fixed key name and context, removed extra $

    defaults:
      run:
        working-directory: terraform                              # hyphen, lowercase folder

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform init
        run: terraform init
      - name: Terraform plan
        run: terraform plan  

      - name: Terraform plan
        run: terraform plan
